#!/bin/bash

echo "* Starting node 2..."
geth --identity "node2" --genesis /etc/eth/customGenesis.json --rpc --rpcport "8001" --rpccorsdomain "*" --datadir "/data/node-2" --port "30304" --nodiscover --ipcapi "admin,db,eth,debug,miner,net,shh,txpool,personal,web3" --rpcapi "db,eth,net,web3" --autodag --networkid 1900 --nat "any" console

