#!/bin/bash

echo "* Starting node 2..."
geth --identity "node2" \
--rpc --rpcaddr "0.0.0.0" --rpcport "8001" --rpccorsdomain "*" \
--ws --wsaddr "0.0.0.0" --wsport "8101" --wsorigins "*" \
--datadir "/data/node-2" --port "30304" --nodiscover --ipcapi "admin,db,eth,debug,miner,net,shh,txpool,personal,web3" --rpcapi "db,eth,net,web3,personal" --autodag --networkid 1900 --nat "any"
