#!/bin/bash

echo "* Starting node 1..."
geth --identity "node1" \
--rpc --rpcaddr "0.0.0.0" --rpcport "8000" --rpccorsdomain "*" --rpcvhosts "*" \
--ws --wsaddr "0.0.0.0" --wsport "8100" --wsorigins "*" \
--datadir "/data/node-1" --port "30303" --nodiscover --rpcapi "db,eth,net,web3,personal" --autodag --networkid 1900 --nat "any" \
--mine --minerthreads=1
